First of all we need to import Pandas library.

In [1]:
import pandas as pd

DataFrame:
It is the table. It is array of individual entries.

In [5]:
pd.DataFrame({"a":[1,2,3],"b":[4,5,6]})

   a  b
0  1  4
1  2  5
2  3  6

In [8]:
pd.DataFrame({"a":["I am Ilyan","I am learning pandas."]})

                       a
0             I am Ilyan
1  I am learning pandas.

This is used with dictionaries.
keys = colomns
values = rows

We can change the index from starting from 0 to any other index.

In [9]:
pd.DataFrame({"A":[1,2,3],"B":[4,5,6]},index=["1","2","3"])

   A  B
1  1  4
2  2  5
3  3  6